### ISSUE TITLE
Computer Vision page figures

### ISSUE THREAD

**Issue by fguney** [kuisailab/ai-media-group#7]
- [x] The 3D figure looks very low quality although I've uploaded a high-res image.

- [x] Can you put figures and text into frames so that it still looks the same shape when the page is resized? Currently, I've just copied them above the text.

I guess this is related to style, right? @birkancelik18

**Comment by birkancelik18** [comment]
Hi Fatma Hocam,
I did some revisions on Computer Vision page could you please check it if the 3D photo and shape issues are corrected?
 if not, could you share the high-res images one more time, please. It seems we should upload photos one more time, because photos were somehow resized by wordPress.

Here is the drive link you could use:
https://drive.google.com/drive/folders/1EhFKNI1s-nEzBwaeKcAUF9wRpMqEMDxv?usp=sharing

**Comment by fguney** [comment]
done! how can we prevent this from happening in the future?

**Comment by birkancelik18** [comment]
I guess, if we use seperate blocks for each different object, blocks will automatically adjust size, shape or other qualities. 
Here is the link that you can find properties of all blocks in wordPress theme we use.
https://drive.google.com/file/d/1w1tBHherMzaiUYYG56Ns8HJjS24EONNx/view?usp=sharing

**Comment by fguney** [comment]
yes, exactly. the question is can you do it or should I do it?

**Comment by birkancelik18** [comment]
I can do revisions, If you share content.
 Could you use drive link above for photos and videos? If you wish I can also create a google document for texts we will add.

**Comment by fguney** [comment]
I've shared the photos, the content will be the same text, you just need to reorganize it into separate frames.

Thanks, and please let me know if there is anything else :)
